name: mlflow-project-env
channels:
  - defaults
  - conda-forge # Tambahkan conda-forge untuk jangkauan paket lebih luas
dependencies:
  - python=3.9 # Cukup spesifikkan versi mayor Python
  - pip
  - pip:
    - mlflow==2.19.0
    - scikit-learn # Biarkan pip menemukan versi kompatibel terbaru
    - pandas      # Biarkan pip menemukan versi kompatibel terbaru
    - numpy       # Biarkan pip menemukan versi kompatibel terbaru
    # Matplotlib dan seaborn tidak perlu di sini untuk modelling.py.
    # Jika nanti di Advanced modelling_tuning.py butuh plotting, kita akan tambahkan lagi.
