name: mlflow-project-env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9.18
  - pip
  - pip:
    - mlflow==2.19.0
    - scikit-learn
    - pandas
    - numpy
    - matplotlib
    - seaborn
