name: Retrain ML Model

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up MLflow Project Environment
      uses: conda-incubator/setup-miniconda@v2
      with:
        miniconda-version: "latest"
        activate-environment: "mlflow-project-env"
        environment-file: MLProject/conda.yaml
        auto-update-conda: true
        python-version: 3.9

    - name: Install MLflow
      shell: bash -l {0} # <--- Tambahkan baris ini
      run: |
        conda activate mlflow-project-env
        pip install mlflow==2.19.0

    - name: Run MLflow Project
      shell: bash -l {0} # <--- Tambahkan baris ini
      run: |
        conda activate mlflow-project-env
        mlflow run MLProject/
